Update - 2020.11.21

diff --git a/EN-uk/Ubuntu - Lubuntu - Xubuntu - elementaryOS - PopOS - ZorinOS - DeepinOS/Scripts/unlocker b/EN-uk/Ubuntu - Lubuntu - Xubuntu - elementaryOS - PopOS - ZorinOS - DeepinOS/Scripts/unlocker
--- a/EN-uk/Ubuntu - Lubuntu - Xubuntu - elementaryOS - PopOS - ZorinOS - DeepinOS/Scripts/unlocker
+++ b/EN-uk/Ubuntu - Lubuntu - Xubuntu - elementaryOS - PopOS - ZorinOS - DeepinOS/Scripts/unlocker
@@ -1,140 +1,114 @@
 #!/bin/sh
 
-# Onglet d'aide.
-if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
-then
-	echo "\e[32m\e[1m*********************\e[0m"
-	echo "\e[32m\e[1m*    INFORMATION    *\e[0m"
-	echo "\e[32m\e[1m*********************\e[0m"
-	echo ""
+Help()
+{
+	echo "\e[32m\e[1m=====================\e[0m"
+	echo "\e[32m\e[1m=    Information    =\e[0m"
+	echo "\e[32m\e[1m=====================\e[0m\n"
 	echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
 	echo "\e[32m\e[1mScript name:\e[0m Unlocker"
 	echo "\e[32m\e[1mCommand:\e[0m     unlocker"
 	echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
 	echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
-	echo "\e[32m\e[1mVersion:\e[0m     1.2.0.20191021"
-	echo ""
-	echo "\e[32m\e[1m****************\e[0m"
-	echo "\e[32m\e[1m*    DETAIL    *\e[0m"
-	echo "\e[32m\e[1m****************\e[0m"
-	echo ""
-	echo "You must execute the script with root permissions."
-	echo ""
-	echo "This script permits to unlock drives that are encrypted with Bitlocker using the 'dislocker' package.\nIt gives a R/W access to the unlocked drive."
-	echo ""
+	echo "\e[32m\e[1mVersion:\e[0m     1.3.0.20201119\n"
+	echo "\e[32m\e[1m================\e[0m"
+	echo "\e[32m\e[1m=    Detail    =\e[0m"
+	echo "\e[32m\e[1m================\e[0m\n"
+	echo "You must execute the script with root permissions.\n"
+	echo "This script permits to unlock drives that are encrypted with Bitlocker using the 'dislocker' package.\nIt gives a R/W access to the unlocked drive.\n"
 	exit 0
-fi
+}
 
-# Vérification des privilèges root de l'utilisateur.
-if [ "$(id -u)" != "0" ]
-	then
-   	echo "\e[31m\e[1mThis script must be executed with root privileges.\e[0m" 1>&2
-   	echo ""
-   	exit 1
-fi
-
-# Déclaration de la variable 'answer' à zéro.
-answer="0"
-
-# Déclaration de la fonction 'CONFIRMATION'.
-CONFIRMATION()
+Confirmation()
 {
 	if [ $answer = "y" ] || [ $answer = "Y" ]
 		then
-            echo "/!\ The decrypted drive will be unmounted. Any unsaved activity on the drive will be lost. /!\ "
-						echo ""
-						read -p "Press any key to continue..." push1
-            echo ""
-            umount /media/"$name"/mount && umount /media/"$name"/bitlocker
-            echo "The folder and the drive has been unmounted."
-						echo ""
-            exit
+      echo "\e[31m\e[1m/!\ The decrypted drive will be unmounted. Any unsaved activity on the drive will be lost. /!\\e[0m\n"
+			read -p "Press any key to continue..." push1
+      umount /media/"$name"/mount && umount /media/"$name"/bitlocker
+      echo "\nThe folder and the drive has been unmounted.\n"
+      exit 0
 	elif [ $answer = "n" ] || [ $answer = "N" ]
 		then
-            echo "The folder and the drive are still mounted."
-            echo "To unmount them, please type the following commands : 'sudo umount /media/"$name"/mount && sudo umount /media/"$name"/bitlocker'"
-            echo ""
-            exit
+      echo "The folder and the drive are still mounted.\nTo unmount them, type the following commands : 'sudo umount /media/"$name"/mount && sudo umount /media/"$name"/bitlocker'\n"
+      exit 0
 	else
-			echo "Please type 'y' or 'n'."
-			echo ""
+			echo "Please type 'y' or 'n'.\n"
 	fi
 }
 
-# Déclaration de la fonction 'UNLOCK'.
-UNLOCK()
+Unlock()
 {
-	# Déclaration du chemin du disque à débloquer.
+	echo ""
 	read -p "Enter the path of the drive to unlock : " path
-
-	# Utilisation de Dislocker pour déverrouiller le disque.
 	dislocker -V "$path" -u -- /media/"$name"/bitlocker
-
-	# Montage du disque dans le dossier mount.
 	mount -w -o loop /media/"$name"/bitlocker/dislocker-file /media/"$name"/mount
+	Relock
 }
 
-echo "\e[32m\e[1m******************\e[0m"
-echo "\e[32m\e[1m*    UNLOCKER    *\e[0m"
-echo "\e[32m\e[1m******************\e[0m"
-echo ""
-
-# Saisie et lecture du nom d'utilisateur.
-echo ""
-read -p "Please type your username : " name
-echo ""
-
-# Vérification de l'existence des dossier 'bitlocker' et 'mount'. S'ils n'existent pas, les créer.
-if [ -d /media/"$name"/bitlocker ]
-then
-	if [ -d /media/"$name"/mount ]
+Verification()
+{
+	if [ -d /media/"$name"/bitlocker ]
 	then
-		UNLOCK
-		echo ""
+		if [ -d /media/"$name"/mount ]
+		then
+			Unlock
+		else
+			mkdir /media/"$name"/mount
+			Unlock
+		fi
 	else
-		echo "The 'mount' folder does not exists and will be created."
-		echo ""
-		mkdir /media/"$name"/mount
-		UNLOCK
-		echo ""
+		mkdir /media/"$name"/bitlocker
+		if [ -d /media/"$name"/mount ]
+		then
+			Unlock
+		else
+			mkdir /media/"$name"/mount
+			Unlock
+		fi
 	fi
-else
-	echo "The 'Bitlocker' folder does not exists and will be created."
+}
+
+Relock()
+{
 	echo ""
-	mkdir /media/"$name"/bitlocker
-	if [ -d /media/"$name"/mount ]
-	then
-		UNLOCK
+	read -p "Press any key to continue..." push0
+	echo ""
+
+	while [ $answer != "y" ] || [ $answer != "Y" ] || [ $answer != "n" ] || [ $answer != "N" ] || [ -z $answer ]
+	do
+		read -p "The script will now unmount the drive and the 'Bitlocker' folder, do you wish to continue ? (y or n) : " answer
 		echo ""
+		if [ $answer = 'y' ] || [ $answer = 'n' ]
+		then
+			break
+		fi
+	done
+
+	if [ $answer = "y" ] || [ $answer = "Y" ] || [ $answer = "n" ] || [ $answer = "N" ]
+	then
+		Confirmation
 	else
-		echo "The 'mount' folder does not exists and will be created."
-		echo ""
-		mkdir /media/"$name"/mount
-		UNLOCK
-		echo ""
+		echo "An unsuspected error has occured.\n"
 	fi
-fi
+}
 
-# Pause.
-echo ""
-read -p "Press any key to continue..." push0
-echo ""
+answer=0
 
-# Demande de confirmation pour démonter le lecteur et le dossier bitlocker.
-while [ $answer != "y" ] || [ $answer != "Y" ] || [ $answer != "n" ] || [ $answer != "N" ] || [ -z $answer ]
-do
-	read -p "The script will now unmount the drive and the 'Bitlocker' folder, do you want to continue ? (y or n) : " answer
-	echo ""
-	if [ $answer = 'y' ] || [ $answer = 'n' ]
-	then
-		break
-	fi
-done
+echo "\e[31m\e[1m******************\e[0m"
+echo "\e[31m\e[1m*    UNLOCKER    *\e[0m"
+echo "\e[31m\e[1m******************\e[0m\n"
 
-# Si oui, exécution de CONFIRMATION.
-if [ $answer = "y" ] || [ $answer = "Y" ] || [ $answer = "n" ] || [ $answer = "N" ]
+if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
 then
-	CONFIRMATION
+	Help
 else
-	echo "An unsuspected error has occured."
+	if [ "$(id -u)" != "0" ]
+		then
+	   	echo "\e[31m\e[1mThis script must be executed with root privileges.\e[0m\n" 1>&2
+	   	exit 1
+		else
+			read -p "Please type your username : " name
+			Verification
+	fi
 fi
diff --git a/EN-uk/Ubuntu - Lubuntu - Xubuntu - elementaryOS - PopOS - ZorinOS - DeepinOS/Scripts/update-git b/EN-uk/Ubuntu - Lubuntu - Xubuntu - elementaryOS - PopOS - ZorinOS - DeepinOS/Scripts/update-git
--- a/EN-uk/Ubuntu - Lubuntu - Xubuntu - elementaryOS - PopOS - ZorinOS - DeepinOS/Scripts/update-git
+++ b/EN-uk/Ubuntu - Lubuntu - Xubuntu - elementaryOS - PopOS - ZorinOS - DeepinOS/Scripts/update-git
@@ -1,93 +1,83 @@
 #!/bin/sh
 
-# Onglet d'aide.
-if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
-then
-  echo "\e[32m\e[1m*********************\e[0m"
-  echo "\e[32m\e[1m*    INFORMATION    *\e[0m"
-  echo "\e[32m\e[1m*********************\e[0m"
-  echo ""
+Help()
+{
+  echo "\e[32m\e[1m=====================\e[0m"
+  echo "\e[32m\e[1m=    Information    =\e[0m"
+  echo "\e[32m\e[1m=====================\e[0m\n"
   echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
   echo "\e[32m\e[1mScript name:\e[0m Update GIT"
   echo "\e[32m\e[1mCommand:\e[0m     update-git"
   echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
   echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
-  echo "\e[32m\e[1mVersion:\e[0m     1.0.2.20200508"
-  echo ""
-  echo "\e[32m\e[1m****************\e[0m"
-  echo "\e[32m\e[1m*    DETAIL    *\e[0m"
-  echo "\e[32m\e[1m****************\e[0m"
-  echo ""
-  echo "You must execute the script with root permissions."
-  echo ""
-  echo "This script automatically updates the cloned GitHub repo of 'Scripts4Linux'."
-  echo ""
+  echo "\e[32m\e[1mVersion:\e[0m     1.1.0.20201120\n"
+  echo "\e[32m\e[1m================\e[0m"
+  echo "\e[32m\e[1m=    Detail    =\e[0m"
+  echo "\e[32m\e[1m================\e[0m\n"
+  echo "You must execute the script with root permissions.\n"
+  echo "This script automatically updates the cloned GitHub repo of 'scripts4linux'.\n"
   exit 0
-fi
+}
 
-# Vérification des privilèges root de l'utilisateur.
-if [ "$(id -u)" != "0" ]
+Update()
+{
+  if [ -d /home/"$name"/scripts4linux ]
   then
-    echo "\e[31m\e[1mThis script must be executed with root privileges.\e[0m" 1>&2
+    rm -rf /home/"$name"/scripts4linux
+    cd /home/"$name"/
+    git clone http://github.com/kalvez/scripts4linux.git
     echo ""
-    exit 1
-fi
+  else
+    cd /home/"$name"/
+  	git clone http://github.com/kalvez/scripts4linux.git
+    echo ""
+  fi
+}
 
-echo "\e[32m\e[1m********************\e[0m"
-echo "\e[32m\e[1m*    UPDATE GIT    *\e[0m"
-echo "\e[32m\e[1m********************\e[0m"
-echo ""
-
-# Mise à zéro des arguments.
-name=0
-answer=0
-
-# Déclaration de la fonction 'INSTALLATION'.
-INSTALLATION()
+Installation()
 {
 	if [ $answer = "y" ] || [ $answer = "Y" ]
 		then
-      cd /home/"$name"/scripts4linux/EN-uk
-      chmod +x auto-installer
-      ./auto-installer
+      chmod +x /home/"$name"/scripts4linux/EN-uk/auto-installer
+      cd /home/"$name"/scripts4linux/EN-uk && ./auto-installer
       echo ""
-      exit
+      exit 0
 	elif [ $answer = "n" ] || [ $answer = "N" ]
 		then
-      echo "The scripts won't be updated."
-      echo ""
-      exit
+      echo "The scripts won't be updated.\n"
+      exit 0
 	else
-			echo "Please type 'y' or 'n'."
-			echo ""
+			echo "Please type 'y' or 'n'.\n"
 	fi
 }
 
-# Saisie et lecture du nom d'utilisateur.
-read -p "Please type your username : " name
-echo ""
+name=0
+answer=0
 
-# Vérification de la présence du dossier 'scripts4linux' sur le disque, et suppression s'il existe, puis clonage du repo GitHub.
-if [ -d /home/"$name"/scripts4linux ]
+echo "\e[31m\e[1m********************\e[0m"
+echo "\e[31m\e[1m*    UPDATE GIT    *\e[0m"
+echo "\e[31m\e[1m********************\e[0m\n"
+
+if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
 then
-  rm -rf /home/"$name"/scripts4linux
-  cd /home/"$name"/
-  git clone http://github.com/kalvez/scripts4linux.git
-  echo ""
-else
-  cd /home/"$name"/
-	git clone http://github.com/kalvez/scripts4linux.git
-  echo ""
+  Help
 fi
 
-# Installation des scripts.
-read -p "Would you like to update the scripts now ? ('y' or 'n') : " answer
-echo ""
-
-if [ $answer = "y" ] || [ $answer = "Y" ] || [ $answer = "n" ] || [ $answer = "N" ]
-then
-  INSTALLATION
-else
-  echo "An unsuspected error has occured."
-  echo ""
+if [ "$(id -u)" != "0" ]
+  then
+    echo "\e[31m\e[1mThis script must be executed with root privileges.\e[0m\n" 1>&2
+    exit 1
+  else
+    read -p "Please type your username : " name
+    echo ""
+    Update
+    read -p "Would you like to update the scripts now ? ('y' or 'n') : " answer
+    echo ""
+    if [ $answer = "y" ] || [ $answer = "Y" ] || [ $answer = "n" ] || [ $answer = "N" ]
+    then
+      Installation
+      echo ""
+    else
+      echo "An unsuspected error has occured.\n"
+    fi
 fi
